apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    # Jump Server - ADMIN access (MUST come first!)
    - rolearn: arn:aws:iam::881605784291:role/dev-varrow-eks-cluster-jump-server-role
      username: jump-server-admin
      groups:
      - system:masters
    
    # Worker Nodes - Regular node access
    - rolearn: arn:aws:iam::881605784291:role/dev-varrow-eks-cluster-eks-node-role
      username: system:node:{{EC2PrivateDNSName}}
      groups:
      - system:bootstrappers
      - system:nodes
