apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::881605784291:role/dev-varrow-eks-cluster-jump-server-role
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- rolearn: arn:aws:iam::881605784291:role/dev-varrow-eks-cluster-jump-server-role\n  groups:\n  - system:bootstrappers\n  - system:nodes\n  username: system:node:{{EC2PrivateDNSName}}\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2026-02-14T13:54:34Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"36792","uid":"17e552f3-4d29-45c5-ad84-03773543339f"}}
  creationTimestamp: "2026-02-14T13:54:34Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "37480"
  uid: 17e552f3-4d29-45c5-ad84-03773543339f
